server:
  port: 8080

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/zzforum?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: https://965720890.auth0.com/
mybatis:
  type-aliases-package: com.graduate.zzforum.entity
  mapper-locations: classpath:mybatis/*.xml

# auth0:
#   domain: 965720890.auth0.com
#   clientId: RFgQ06spECDAGqwoKQNDoblvJZH8DLj6
#   clientSecret: JKKLJOoasdlfj
jwt: 
  key: RFgQ06spECDAGqwoKQNDoblvJZH8DLj6
  ttl: 3600000